version: "1.0"
info:
  model: int-scaffold
packages:
- name: KMAT_RAHUL_28JUNProject
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm/KMAT_RAHUL_28JUNProject
  gitUsername: karthikbm
  gitBranch: main
- name: KMATWorkdayTest
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: TestWorkdayConnector
  version: "1.0"
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: OriginKMAT_Jun2024
  version: "1.0"
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: TestAWSS3Connr
  version: "1.0"
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
services:
- serviceName: project.kmat_rahul_28jun.integrations:workdaykmattest
  packages:
  - name: KMAT_RAHUL_28JUNProject
    version: "1.0"
  - name: TestWorkdayConnector
    version: "1.0"
  - name: WmWorkdayProvider
    version: 10.7.0.0.11
- serviceName: ccs:Get_Organizations
  packages:
  - name: TestWorkdayConnector
    version: "1.0"
  - name: WmWorkdayProvider
    version: 10.7.0.0.11
- serviceName: project.kmat_rahul_28jun.integrations:AWS_Listbuckets
  packages:
  - name: KMAT_RAHUL_28JUNProject
    version: "1.0"
  - name: WmAmazonS3Provider
    version: 10.7.0.0.9
  - name: TestWorkdayConnector
    version: "1.0"
  - name: WmWorkdayProvider
    version: 10.7.0.0.11
  - name: AWS_KMAT
    version: "1.0"
  - name: OriginKMAT_Jun2024
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.29
  - name: TestAWSS3Connr
    version: "1.0"
- serviceName: AWS_CCS:ListBuckets
  packages:
  - name: AWS_KMAT
    version: "1.0"
  - name: WmAmazonS3Provider
    version: 10.7.0.0.9
- serviceName: CCS:ListBuckets
  packages:
  - name: TestAWSS3Connr
    version: "1.0"
